In [2]:
%pip install pandas numpy scikit-learn matplotlib seaborn

Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp311-cp311-win_amd64.whl.metadata (80 kB)
     ---------------------------------------- 0.0/80.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/80.3 kB ? eta -:--:--
     --------------- ------------------------ 30.7/80.3 kB ? eta -:--:--
     --------------- ------------------------ 30.7/80.3 kB ? eta -:--:--
     --------------- ------------------------ 30.7/80.3 kB ? eta -:--:--
     --------------- ------------------------ 30.7/80.3 kB ? eta -:--:--
     -------------------------------------- 80.3/80.3 kB 344.9 kB/s eta 0:00:00
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.63.0-cp311-cp311-win_amd64.whl.metadata (121 kB)
     ---------------------------------------- 0.0/121.0 kB ? eta -:--:--
     --- ------------------------------------ 10.2/121.0 kB ? eta -:--:--
     ----------------------------------- -- 112.6/121.0 kB 1.6 MB/s eta 0:00:01
     -------------------------------------- 121.0/121.0 kB 1.4 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
    --------------------------------------- 0.2/10.0 MB 4.8 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/10.0 MB 5.2 MB/s eta 0:00:02
   --- ------------------------------------ 0.8/10.0 MB 5.4 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/10.0 MB 4.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.1/10.0 MB 5.0 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/10.0 MB 4.5 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/10.0 MB 4.3 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/10.0 MB 4.2 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/10.0 MB 4.1 MB/s eta 0:00:02
   ------- -------------------------------- 1.9/10.0 MB 4.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/10.0 MB 4.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.2/10.0 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/10.0 MB 3.8 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/10.0 MB 3.8 MB/s eta 0:00:02
   ---------- ----------------------------- 2.7/10.0 MB 3.8 MB/s eta 0:00:02
   ----------- ---------------------------- 2.8/10.0 MB 3.7 MB/s eta 0:00:02
   ----------- ---------------------------- 3.0/10.0 MB 3.7 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/10.0 MB 3.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.2/10.0 MB 3.5 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/10.0 MB 3.5 MB/s eta 0:00:02
   -------------- ------------------------- 3.5/10.0 MB 3.4 MB/s eta 0:00:02
   -------------- ------------------------- 3.6/10.0 MB 3.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.8/10.0 MB 3.4 MB/s eta 0:00:02
   ---------------- ----------------------- 4.0/10.0 MB 3.5 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/10.0 MB 3.5 MB/s eta 0:00:02
   ----------------- ---------------------- 4.4/10.0 MB 3.5 MB/s eta 0:00:02
   ------------------ --------------------- 4.6/10.0 MB 3.5 MB/s eta 0:00:02
   ------------------ --------------------- 4.7/10.0 MB 3.5 MB/s eta 0:00:02
   ------------------- -------------------- 4.9/10.0 MB 3.5 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/10.0 MB 3.5 MB/s eta 0:00:02
   -------------------- ------------------- 5.2/10.0 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.3/10.0 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.5/10.0 MB 3.5 MB/s eta 0:00:02
   ---------------------- ----------------- 5.6/10.0 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/10.0 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.9/10.0 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.1/10.0 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.2/10.0 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/10.0 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 6.4/10.0 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/10.0 MB 3.3 MB/s eta 0:00:02
   --------------------------- ------------ 6.7/10.0 MB 3.4 MB/s eta 0:00:01
   --------------------------- ------------ 6.9/10.0 MB 3.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/10.0 MB 3.4 MB/s eta 0:00:01
   ----------------------------- ---------- 7.2/10.0 MB 3.4 MB/s eta 0:00:01
   ----------------------------- ---------- 7.4/10.0 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.5/10.0 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.7/10.0 MB 3.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.8/10.0 MB 3.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/10.0 MB 3.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/10.0 MB 3.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.2/10.0 MB 3.2 MB/s eta 0:00:01
   --------------------------------- ------ 8.3/10.0 MB 3.2 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/10.0 MB 3.2 MB/s eta 0:00:01
   ---------------------------------- ----- 8.6/10.0 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.8/10.0 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 9.0/10.0 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.4/10.0 MB 3.2 MB/s eta 0:00:01
   -------------------------------------- - 9.6/10.0 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  9.8/10.0 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 3.3 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB 8.9 MB/s eta 0:00:02
   - -------------------------------------- 0.5/12.6 MB 5.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.7/12.6 MB 6.8 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/12.6 MB 5.6 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.6 MB 4.9 MB/s eta 0:00:03
   --- ------------------------------------ 1.1/12.6 MB 4.8 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.6 MB 4.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.4/12.6 MB 4.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/12.6 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/12.6 MB 4.1 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/12.6 MB 3.9 MB/s eta 0:00:03
   ------ --------------------------------- 2.0/12.6 MB 3.8 MB/s eta 0:00:03
   ------ --------------------------------- 2.2/12.6 MB 3.7 MB/s eta 0:00:03
   ------- -------------------------------- 2.3/12.6 MB 3.7 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.6 MB 3.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.5/12.6 MB 3.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 3.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.8/12.6 MB 3.4 MB/s eta 0:00:03
   --------- ------------------------------ 3.0/12.6 MB 3.5 MB/s eta 0:00:03
   ---------- ----------------------------- 3.2/12.6 MB 3.5 MB/s eta 0:00:03
   ---------- ----------------------------- 3.3/12.6 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 3.5/12.6 MB 3.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.6/12.6 MB 3.4 MB/s eta 0:00:03
   ------------ --------------------------- 3.8/12.6 MB 3.4 MB/s eta 0:00:03
   ------------ --------------------------- 4.0/12.6 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.3/12.6 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.6/12.6 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 4.8/12.6 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 4.9/12.6 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.6 MB 3.4 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.6 MB 3.3 MB/s eta 0:00:03
   ---------------- ----------------------- 5.3/12.6 MB 3.3 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.6 MB 3.3 MB/s eta 0:00:03
   ----------------- ---------------------- 5.7/12.6 MB 3.4 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.6 MB 3.3 MB/s eta 0:00:03
   ------------------ --------------------- 5.9/12.6 MB 3.3 MB/s eta 0:00:03
   ------------------- -------------------- 6.1/12.6 MB 3.3 MB/s eta 0:00:02
   ------------------- -------------------- 6.2/12.6 MB 3.3 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.6 MB 3.3 MB/s eta 0:00:02
   -------------------- ------------------- 6.5/12.6 MB 3.3 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.6 MB 3.3 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 6.9/12.6 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 7.2/12.6 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.4/12.6 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.5/12.6 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 7.7/12.6 MB 3.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.7/12.6 MB 3.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.8/12.6 MB 3.2 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.6 MB 3.1 MB/s eta 0:00:02
   ------------------------- -------------- 8.0/12.6 MB 3.1 MB/s eta 0:00:02
   ------------------------- -------------- 8.0/12.6 MB 3.1 MB/s eta 0:00:02
   ------------------------- -------------- 8.2/12.6 MB 3.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.3/12.6 MB 3.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.3/12.6 MB 3.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 3.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.5/12.6 MB 3.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.6 MB 3.0 MB/s eta 0:00:02
   ---------------------------- ----------- 8.8/12.6 MB 3.0 MB/s eta 0:00:02
   ---------------------------- ----------- 9.0/12.6 MB 3.0 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 3.0 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.6 MB 3.0 MB/s eta 0:00:02
   ------------------------------ --------- 9.6/12.6 MB 3.1 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 3.1 MB/s eta 0:00:01
   ------------------------------- -------- 9.9/12.6 MB 3.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.1/12.6 MB 3.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.3/12.6 MB 3.1 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 3.1 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.6 MB 3.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.8/12.6 MB 3.1 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 3.0 MB/s eta 0:00:01
   ----------------------------------- ---- 11.1/12.6 MB 3.1 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------ --- 11.4/12.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------ --- 11.6/12.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.7/12.6 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.9/12.6 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 12.0/12.6 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 12.2/12.6 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  12.5/12.6 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 3.0 MB/s eta 0:00:00
Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
    --------------------------------------- 0.1/8.3 MB 4.3 MB/s eta 0:00:02
   - -------------------------------------- 0.3/8.3 MB 2.9 MB/s eta 0:00:03
   - -------------------------------------- 0.4/8.3 MB 3.0 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/8.3 MB 3.2 MB/s eta 0:00:03
   --- ------------------------------------ 0.7/8.3 MB 3.4 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/8.3 MB 3.3 MB/s eta 0:00:03
   ---- ----------------------------------- 0.9/8.3 MB 3.5 MB/s eta 0:00:03
   ----- ---------------------------------- 1.1/8.3 MB 3.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.3 MB 3.3 MB/s eta 0:00:03
   ------- -------------------------------- 1.5/8.3 MB 3.4 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/8.3 MB 3.4 MB/s eta 0:00:02
   --------- ------------------------------ 1.9/8.3 MB 3.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.3 MB 3.6 MB/s eta 0:00:02
   ---------- ----------------------------- 2.2/8.3 MB 3.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.3 MB 3.5 MB/s eta 0:00:02
   ------------ --------------------------- 2.5/8.3 MB 3.4 MB/s eta 0:00:02
   ------------- -------------------------- 2.7/8.3 MB 3.4 MB/s eta 0:00:02
   ------------- -------------------------- 2.9/8.3 MB 3.5 MB/s eta 0:00:02
   -------------- ------------------------- 3.0/8.3 MB 3.5 MB/s eta 0:00:02
   --------------- ------------------------ 3.2/8.3 MB 3.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.2/8.3 MB 3.3 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.3 MB 3.3 MB/s eta 0:00:02
   ----------------- ---------------------- 3.5/8.3 MB 3.3 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.3 MB 3.3 MB/s eta 0:00:02
   ------------------ --------------------- 3.9/8.3 MB 3.3 MB/s eta 0:00:02
   ------------------- -------------------- 4.0/8.3 MB 3.3 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.3 MB 3.3 MB/s eta 0:00:02
   --------------------- ------------------ 4.4/8.3 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 4.6/8.3 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 4.7/8.3 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 4.8/8.3 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.3 MB 3.3 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.3 MB 3.3 MB/s eta 0:00:01
   ------------------------- -------------- 5.3/8.3 MB 3.3 MB/s eta 0:00:01
   -------------------------- ------------- 5.5/8.3 MB 3.3 MB/s eta 0:00:01
   --------------------------- ------------ 5.6/8.3 MB 3.3 MB/s eta 0:00:01
   --------------------------- ------------ 5.7/8.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------- ----------- 5.9/8.3 MB 3.3 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 6.2/8.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 6.4/8.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------- -------- 6.5/8.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------- ------- 6.7/8.3 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 6.9/8.3 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 7.0/8.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.3 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.3 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.5/8.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 7.6/8.3 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 7.7/8.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.3 MB 3.2 MB/s eta 0:00:01
   -------------------------------------- - 8.0/8.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 3.2 MB/s eta 0:00:00
Downloading matplotlib-3.11.1-cp311-cp311-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.3 MB 3.3 MB/s eta 0:00:03
   - -------------------------------------- 0.3/9.3 MB 2.9 MB/s eta 0:00:04
   - -------------------------------------- 0.5/9.3 MB 3.1 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/9.3 MB 3.4 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/9.3 MB 3.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.3 MB 3.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.2/9.3 MB 3.8 MB/s eta 0:00:03
   ------ --------------------------------- 1.4/9.3 MB 3.8 MB/s eta 0:00:03
   ------- -------------------------------- 1.7/9.3 MB 3.9 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.3 MB 3.8 MB/s eta 0:00:02

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

print("Pandas is working!")
print("Pandas version:", pd.__version__)

Pandas is working!
Pandas version: 3.0.5

In [2]:
import pandas as pd

train_df = pd.read_csv("../data/raw/train.csv")

print("Training data shape:", train_df.shape)
train_df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/train.csv'

In [3]:
import pandas as pd

train_df = pd.read_csv("../data/raw/train.csv")

print("Training data shape:", train_df.shape)
train_df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/train.csv'

In [5]:
import pandas as pd

train_df = pd.read_csv("../data/raw/train_csv.csv")

print("Training data shape:", train_df.shape)
train_df.head()

Training data shape: (440833, 12)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [6]:
test_df = pd.read_csv("../data/raw/test_csv.csv")

print("Training data shape:", train_df.shape)
print("Testing data shape:", test_df.shape)

Training data shape: (440833, 12)
Testing data shape: (64374, 12)

In [7]:
print("Training columns:")
print(train_df.columns.tolist())

print("\nFirst 5 training records:")
display(train_df.head())

Training columns:
['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

First 5 training records:

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [8]:
print("Testing columns:")
print(test_df.columns.tolist())

print("\nFirst 5 testing records:")
display(test_df.head())

Testing columns:
['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

First 5 testing records:

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [9]:
print("Training dataset:", train_df.shape)
print("Testing dataset:", test_df.shape)

Training dataset: (440833, 12)
Testing dataset: (64374, 12)

In [10]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

In [11]:
missing = train_df.isnull().sum()

print("Missing values:")
print(missing[missing > 0])

Missing values:
CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [12]:
print("Duplicate rows:", train_df.duplicated().sum())

Duplicate rows: 0

In [13]:
print(train_df.columns.tolist())

['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

In [15]:
TARGET = "Churn"

In [16]:
X = train_df.drop(columns=[TARGET])
y = train_df[TARGET]

X_test = test_df.drop(columns=[TARGET])
y_test = test_df[TARGET]

print("Training features:", X.shape)
print("Training target:", y.shape)
print("Testing features:", X_test.shape)
print("Testing target:", y_test.shape)

Training features: (440833, 11)
Training target: (440833,)
Testing features: (64374, 11)
Testing target: (64374,)

In [17]:
numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

print("Numerical columns:")
print(numeric_cols)

print("\nCategorical columns:")
print(categorical_cols)

Numerical columns:
['CustomerID', 'Age', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction']

Categorical columns:
['Gender', 'Subscription Type', 'Contract Length']

C:\Users\Dell\AppData\Local\Temp\ipykernel_13872\4274721545.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

In [18]:
print(train_df.columns.tolist())

['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

In [19]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

In [20]:
print(train_df.columns.tolist())

['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

In [26]:
TARGET = "Churn"

In [27]:
X = train_df.drop(columns=[TARGET])
y = train_df[TARGET]

X_test = test_df.drop(columns=[TARGET])
y_test = test_df[TARGET]

print("X:", X.shape)
print("y:", y.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X: (440833, 11)
y: (440833,)
X_test: (64374, 11)
y_test: (64374,)

In [29]:
id_cols = [
    col for col in X.columns
    if "id" in col.lower()
]

print("ID columns found:", id_cols)

X = X.drop(columns=id_cols, errors="ignore")
X_test = X_test.drop(columns=id_cols, errors="ignore")

ID columns found: []

In [30]:
numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_cols = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Numerical:", numeric_cols)
print("Categorical:", categorical_cols)

Numerical: ['Age', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction']
Categorical: ['Gender', 'Subscription Type', 'Contract Length']

C:\Users\Dell\AppData\Local\Temp\ipykernel_13872\3835684495.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_cols),
    ("categorical", categorical_pipeline, categorical_cols)
])

print("Preprocessing pipeline created successfully.")

Preprocessing pipeline created successfully.

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(
        n_estimators=150,
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        random_state=42
    )
}

print("Models ready:", list(models.keys()))

Models ready: ['Logistic Regression', 'Random Forest', 'Gradient Boosting']

In [40]:
print("X shape:", X.shape)
print("X_test shape:", X_test.shape)
print("y shape:", y.shape)
print("y_test shape:", y_test.shape)

print("\nTarget values:")
print(y.value_counts())

X shape: (440833, 10)
X_test shape: (64374, 10)
y shape: (440833,)
y_test shape: (64374,)

Target values:
Churn
1.0    249999
0.0    190833
Name: count, dtype: int64

In [41]:
print("Target data type:", y.dtype)
print("Test target data type:", y_test.dtype)

Target data type: float64
Test target data type: int64

In [42]:
print("X columns:")
print(X.columns.tolist())

X columns:
['Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction']

In [43]:
print("Categorical columns:")
print(categorical_cols)

print("\nNumerical columns:")
print(numeric_cols)

Categorical columns:
['Gender', 'Subscription Type', 'Contract Length']

Numerical columns:
['Age', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction']

In [44]:
print("Target values:")
print(y.value_counts())

print("\nTest target values:")
print(y_test.value_counts())

Target values:
Churn
1.0    249999
0.0    190833
Name: count, dtype: int64

Test target values:
Churn
0    33881
1    30493
Name: count, dtype: int64

In [46]:
print("ALL COLUMNS:")
print(train_df.columns.tolist())

ALL COLUMNS:
['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

In [47]:
print("\nPossible target columns:")
for col in train_df.columns:
    print(col, "->", train_df[col].nunique(), "unique values")

Possible target columns:
CustomerID -> 440832 unique values
Age -> 48 unique values
Gender -> 2 unique values
Tenure -> 60 unique values
Usage Frequency -> 30 unique values
Support Calls -> 11 unique values
Payment Delay -> 31 unique values
Subscription Type -> 3 unique values
Contract Length -> 3 unique values
Total Spend -> 68363 unique values
Last Interaction -> 30 unique values
Churn -> 2 unique values

In [48]:
TARGET = "Churn"

In [49]:
TARGET = "Churn"

X = train_df.drop(columns=[TARGET])
y = train_df[TARGET]

X_test = test_df.drop(columns=[TARGET])
y_test = test_df[TARGET]

print("X:", X.shape)
print("y:", y.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X: (440833, 11)
y: (440833,)
X_test: (64374, 11)
y_test: (64374,)

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Remove ID-like columns
id_cols = [col for col in X.columns if "id" in col.lower()]

X = X.drop(columns=id_cols, errors="ignore")
X_test = X_test.drop(columns=id_cols, errors="ignore")

# Identify column types
numeric_cols = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_cols = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_cols),
    ("categorical", categorical_pipeline, categorical_cols)
])

print("Preprocessing ready!")

Preprocessing ready!

C:\Users\Dell\AppData\Local\Temp\ipykernel_13872\3203566929.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(

In [52]:
# Remove rows where the target value is missing

train_mask = y.notna()

X_clean = X.loc[train_mask].copy()
y_clean = y.loc[train_mask].copy()

print("Original training rows:", len(y))
print("Rows after removing missing targets:", len(y_clean))
print("Missing target values:", y_clean.isna().sum())

Original training rows: 440833
Rows after removing missing targets: 440832
Missing target values: 0

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        random_state=42
    )
}

results = []

for name, model in models.items():

    print(f"\nTraining {name}...")

    pipeline = Pipeline([
        ("preprocessing", preprocessor),
        ("model", model)
    ])

    pipeline.fit(X_clean, y_clean)

    predictions = pipeline.predict(X_test)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, predictions),
        "Precision": precision_score(
            y_test, predictions,
            average="weighted",
            zero_division=0
        ),
        "Recall": recall_score(
            y_test, predictions,
            average="weighted",
            zero_division=0
        ),
        "F1 Score": f1_score(
            y_test, predictions,
            average="weighted",
            zero_division=0
        )
    })

results_df = pd.DataFrame(results)

print("\n===== MODEL COMPARISON =====")
display(results_df.sort_values("F1 Score", ascending=False))

Training Logistic Regression...

Training Random Forest...

Training Gradient Boosting...

===== MODEL COMPARISON =====

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.571302   0.753057  0.571302  0.494936
2    Gradient Boosting  0.506214   0.745777  0.506214  0.373814
1        Random Forest  0.503977   0.747573  0.503977  0.369071

In [54]:
best_model_name = results_df.loc[
    results_df["F1 Score"].idxmax(),
    "Model"
]

print("Best Model:", best_model_name)

Best Model: Logistic Regression

In [55]:
best_model = models[best_model_name]

final_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", best_model)
])

final_pipeline.fit(X_clean, y_clean)

print("Final model trained successfully!")

Final model trained successfully!

In [56]:
import joblib

joblib.dump(
    final_pipeline,
    "../models/churn_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
results_df.to_csv(
    "../models/model_comparison.csv",
    index=False
)fre

print("Model comparison saved successfully!")

Model comparison saved successfully!

In [59]:
import sys

!{sys.executable} -m pip install mlflow

Collecting mlflow
  Using cached mlflow-3.15.1-py3-none-any.whl.metadata (49 kB)
Collecting mlflow-skinny==3.15.1 (from mlflow)
  Using cached mlflow_skinny-3.15.1-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.15.1 (from mlflow)
  Using cached mlflow_tracing-3.15.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Collecting Flask<4 (from mlflow)
  Using cached flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4,>=3.7.0 (from mlflow)
  Downloading aiohttp-3.14.3-cp311-cp311-win_amd64.whl.metadata (8.5 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Using cached alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting cryptography<50,>=43.0.0 (from mlflow)
  Using cached cryptography-49.0.0-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Using cached huey-3.3.4-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: matplotlib<4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: numpy<3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (2.4.6)
Collecting pandas<3 (from mlflow)
  Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting pyarrow<26,>=4.0.0 (from mlflow)
  Downloading pyarrow-25.0.1-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: scikit-learn<2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (1.9.0)
Requirement already satisfied: scipy<2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (1.17.1)
Collecting skops<1 (from mlflow)
  Using cached skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.51-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached cachetools-7.1.7-py3-none-any.whl.metadata (5.5 kB)
Collecting click<9,>=7.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting cloudpickle<4 (from mlflow-skinny==3.15.1->mlflow)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached databricks_sdk-0.125.0-py3-none-any.whl.metadata (44 kB)
Collecting fastapi<1 (from mlflow-skinny==3.15.1->mlflow)
  Using cached fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.15.1->mlflow)
  Downloading gitpython-3.1.59-py3-none-any.whl.metadata (13 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached opentelemetry_api-1.44.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached opentelemetry_proto-1.44.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached opentelemetry_sdk-1.44.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in c:\users\dell\appdata\roaming\python\python311\site-packages (from mlflow-skinny==3.15.1->mlflow) (26.3)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pydantic<3,>=2.0.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Collecting pyyaml<7,>=5.1 (from mlflow-skinny==3.15.1->mlflow)
  Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Collecting requests<3,>=2.17.3 (from mlflow-skinny==3.15.1->mlflow)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting starlette<2 (from mlflow-skinny==3.15.1->mlflow)
  Using cached starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from mlflow-skinny==3.15.1->mlflow) (4.16.0)
Collecting uvicorn<1 (from mlflow-skinny==3.15.1->mlflow)
  Using cached uvicorn-0.52.1-py3-none-any.whl.metadata (6.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading propcache-0.5.2-cp311-cp311-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading yarl-1.24.5-cp311-cp311-win_amd64.whl.metadata (107 kB)
     ---------------------------------------- 0.0/107.2 kB ? eta -:--:--
     -------------------------------------- 107.2/107.2 kB 3.1 MB/s eta 0:00:00
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Using cached mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Collecting cffi>=2.0.0 (from cryptography<50,>=43.0.0->mlflow)
  Downloading cffi-2.1.1-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)
  Downloading pywin32-312-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting urllib3>=1.26.0 (from docker<8,>=4.0.0->mlflow)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting blinker>=1.9.0 (from Flask<4->mlflow)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from Flask<4->mlflow)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from Flask<4->mlflow)
  Using cached markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow)
  Using cached werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=9 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (3.3.2)
Collecting pytz>=2020.1 (from pandas<3->mlflow)
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas<3->mlflow) (2026.3)
Requirement already satisfied: joblib>=1.4.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2->mlflow) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Using cached prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Downloading greenlet-3.5.4-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: colorama in c:\users\dell\appdata\roaming\python\python311\site-packages (from click<9,>=7.0->mlflow-skinny==3.15.1->mlflow) (0.4.6)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow)
  Using cached google_auth-2.56.3-py3-none-any.whl.metadata (6.0 kB)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.15.1->mlflow)
  Using cached protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting typing-inspection>=0.4.2 (from fastapi<1->mlflow-skinny==3.15.1->mlflow)
  Downloading typing_inspection-0.4.3-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.15.1->mlflow)
  Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.1->mlflow)
  Using cached zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Collecting opentelemetry-semantic-conventions==0.65b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.1->mlflow)
  Using cached opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow)
  Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow)
  Downloading pydantic_core-2.46.4-cp311-cp311-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow)
  Downloading charset_normalizer-3.4.9-cp311-cp311-win_amd64.whl.metadata (42 kB)
     ---------------------------------------- 0.0/42.5 kB ? eta -:--:--
     ---------------------------------------- 42.5/42.5 kB 2.0 MB/s eta 0:00:00
Collecting idna<4,>=2.5 (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting anyio<5,>=3.6.2 (from starlette<2->mlflow-skinny==3.15.1->mlflow)
  Using cached anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting h11>=0.8 (from uvicorn<1->mlflow-skinny==3.15.1->mlflow)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow)
  Using cached smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow)
  Using cached pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Using cached mlflow-3.15.1-py3-none-any.whl (11.2 MB)
Using cached mlflow_skinny-3.15.1-py3-none-any.whl (3.6 MB)
Using cached mlflow_tracing-3.15.1-py3-none-any.whl (1.8 MB)
Downloading aiohttp-3.14.3-cp311-cp311-win_amd64.whl (481 kB)
   ---------------------------------------- 0.0/481.1 kB ? eta -:--:--
   --------- ------------------------------ 112.6/481.1 kB 3.3 MB/s eta 0:00:01
   ----------------------- ---------------- 286.7/481.1 kB 3.5 MB/s eta 0:00:01
   ---------------------------------------  471.0/481.1 kB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 481.1/481.1 kB 3.4 MB/s eta 0:00:00
Using cached alembic-1.19.1-py3-none-any.whl (265 kB)
Using cached cryptography-49.0.0-cp311-abi3-win_amd64.whl (3.8 MB)
Using cached docker-7.2.0-py3-none-any.whl (148 kB)
Using cached flask-3.1.3-py3-none-any.whl (103 kB)
Using cached flask_cors-6.0.5-py3-none-any.whl (16 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached huey-3.3.4-py3-none-any.whl (123 kB)
Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 4.4 MB/s eta 0:00:03
   - -------------------------------------- 0.4/11.3 MB 4.6 MB/s eta 0:00:03
   -- ------------------------------------- 0.7/11.3 MB 5.2 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/11.3 MB 5.3 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/11.3 MB 4.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.2/11.3 MB 4.8 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/11.3 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.5/11.3 MB 4.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.3 MB 4.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/11.3 MB 3.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.0/11.3 MB 4.0 MB/s eta 0:00:03
   ------- -------------------------------- 2.2/11.3 MB 3.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.3 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.5/11.3 MB 4.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.7/11.3 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 2.9/11.3 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/11.3 MB 3.9 MB/s eta 0:00:03
   ----------- ---------------------------- 3.2/11.3 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.3/11.3 MB 3.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.5/11.3 MB 3.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.6/11.3 MB 3.7 MB/s eta 0:00:03
   ------------- -------------------------- 3.8/11.3 MB 3.7 MB/s eta 0:00:03
   -------------- ------------------------- 4.0/11.3 MB 3.7 MB/s eta 0:00:03
   -------------- ------------------------- 4.1/11.3 MB 3.7 MB/s eta 0:00:02
   --------------- ------------------------ 4.3/11.3 MB 3.6 MB/s eta 0:00:02
   --------------- ------------------------ 4.4/11.3 MB 3.6 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.3 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.3 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.8/11.3 MB 3.6 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.3 MB 3.5 MB/s eta 0:00:02
   ------------------ --------------------- 5.1/11.3 MB 3.5 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.3 MB 3.5 MB/s eta 0:00:02
   ------------------ --------------------- 5.4/11.3 MB 3.5 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.3 MB 3.5 MB/s eta 0:00:02
   ------------------- -------------------- 5.7/11.3 MB 3.5 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.3 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.3 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 6.2/11.3 MB 3.5 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.3 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 6.5/11.3 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.3 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 6.7/11.3 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.9/11.3 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 7.0/11.3 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 7.2/11.3 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 7.4/11.3 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 7.5/11.3 MB 3.4 MB/s eta 0:00:02
   --------------------------- ------------ 7.7/11.3 MB 3.4 MB/s eta 0:00:02
   --------------------------- ------------ 7.8/11.3 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 8.0/11.3 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 8.0/11.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------- ----------- 8.2/11.3 MB 3.3 MB/s eta 0:00:01
   ----------------------------- ---------- 8.3/11.3 MB 3.4 MB/s eta 0:00:01
   ----------------------------- ---------- 8.5/11.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 8.6/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.8/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 9.1/11.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------- ------- 9.2/11.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------- ------- 9.3/11.3 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 9.5/11.3 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 9.6/11.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------- ----- 9.8/11.3 MB 3.3 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 3.3 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 10.3/11.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.6/11.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 10.9/11.3 MB 3.2 MB/s eta 0:00:01
   -------------------------------------- - 10.9/11.3 MB 3.2 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.3 MB 3.2 MB/s eta 0:00:01

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas'.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
import sys

print("Python being used:")
print(sys.executable)

!{sys.executable} -m pip install mlflow

Python being used:
c:\Users\Dell\AppData\Local\Programs\Python\Python311\python.exe
Requirement already satisfied: mlflow in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (3.15.1)
Requirement already satisfied: mlflow-skinny==3.15.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.15.1)
Requirement already satisfied: mlflow-tracing==3.15.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.15.1)
Requirement already satisfied: Flask-CORS<7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.14.3)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (1.19.1)
Requirement already satisfied: cryptography<50,>=43.0.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (49.0.0)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<4,>=2.5.4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.3.4)
Requirement already satisfied: matplotlib<4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: numpy<3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (2.4.6)
Requirement already satisfied: pandas<3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<26,>=4.0.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (25.0.1)
Requirement already satisfied: scikit-learn<2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (1.9.0)
Requirement already satisfied: scipy<2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (1.17.1)
Requirement already satisfied: skops<1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (2.0.51)
Requirement already satisfied: waitress<4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (7.1.7)
Requirement already satisfied: click<9,>=7.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.125.0)
Requirement already satisfied: fastapi<1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.141.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.59)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: packaging<27 in c:\users\dell\appdata\roaming\python\python311\site-packages (from mlflow-skinny==3.15.1->mlflow) (26.3)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (2.34.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.6.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from mlflow-skinny==3.15.1->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.52.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.5)
Requirement already satisfied: Mako in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.4.1)
Requirement already satisfied: cffi>=2.0.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.1)
Requirement already satisfied: pywin32>=304 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from docker<8,>=4.0.0->mlflow) (312)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.7.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=9 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas<3->mlflow) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas<3->mlflow) (2026.3)
Requirement already satisfied: joblib>=1.4.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2->mlflow) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.4)
Requirement already satisfied: pycparser in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: colorama in c:\users\dell\appdata\roaming\python\python311\site-packages (from click<9,>=7.0->mlflow-skinny==3.15.1->mlflow) (0.4.6)
Requirement already satisfied: google-auth~=2.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (2.56.3)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.4.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.0.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.1->mlflow) (4.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.65b0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.1->mlflow) (0.65b0)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (2026.7.22)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from starlette<2->mlflow-skinny==3.15.1->mlflow) (4.14.2)
Requirement already satisfied: h11>=0.8 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from uvicorn<1->mlflow-skinny==3.15.1->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.6.4)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import mlflow

print("MLflow version:", mlflow.__version__)
print("MLflow is working!")

MLflow version: 3.15.1
MLflow is working!

In [64]:
mlflow.set_experiment("ChurnShield_Model_Experiments")

print("MLflow experiment created!")

2026/08/10 18:23:16 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/08/10 18:23:16 INFO mlflow.store.db.utils: Updating database tables
2026/08/10 18:23:19 INFO mlflow.tracking.fluent: Experiment with name 'ChurnShield_Model_Experiments' does not exist. Creating a new experiment.

MLflow experiment created!

In [65]:
import mlflow

for name, model in models.items():

    with mlflow.start_run(run_name=name):

        pipeline = Pipeline([
            ("preprocessing", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_clean, y_clean)

        predictions = pipeline.predict(X_test)

        accuracy = accuracy_score(y_test, predictions)
        precision = precision_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )
        recall = recall_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )
        f1 = f1_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )

        mlflow.log_param("model", name)
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        print(f"{name} logged successfully")

print("All models logged to MLflow!")

Logistic Regression logged successfully
Random Forest logged successfully
Gradient Boosting logged successfully
All models logged to MLflow!

In [66]:
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

mlflow.set_experiment("ChurnShield_Model_Experiments")

print("MLflow connected successfully!")

2026/08/10 22:19:19 INFO mlflow.tracking.fluent: Experiment with name 'ChurnShield_Model_Experiments' does not exist. Creating a new experiment.

MLflow connected successfully!

In [67]:
with mlflow.start_run():
    mlflow.log_param("test", "ChurnShield")
    mlflow.log_metric("accuracy", 0.85)

print("Test run logged successfully!")

🏃 View run fun-swan-541 at: http://127.0.0.1:5000/#/experiments/1/runs/cb8e104a08f644518a328f322f49f751
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Test run logged successfully!

In [68]:
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

with mlflow.start_run():
    mlflow.log_param("model", "Test_Model")
    mlflow.log_metric("accuracy", 0.85)
    
print("MLflow test run created successfully!")

🏃 View run upset-bug-208 at: http://127.0.0.1:5000/#/experiments/1/runs/6273abe81a5141859f3d2866ce087ea2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
MLflow test run created successfully!

In [72]:
# Check missing values in target
print("Target column:", target)
print("Missing values in training target:", train_df[target].isna().sum())
print("Missing values in testing target:", test_df[target].isna().sum())

Target column: Churn
Missing values in training target: 1
Missing values in testing target: 0

In [75]:
# -----------------------------
# Separate features and target
# -----------------------------

# Remove rows where target is missing
train_clean = train_df.dropna(subset=[target]).copy()
test_clean = test_df.dropna(subset=[target]).copy()

X_train = train_clean.drop(columns=[target])
y_train = train_clean[target]

X_test = test_clean.drop(columns=[target])
y_test = test_clean[target]

print("Training data after cleaning:", X_train.shape)
print("Testing data after cleaning:", X_test.shape)
print("NaN in y_train:", y_train.isna().sum())
print("NaN in y_test:", y_test.isna().sum())

Training data after cleaning: (440832, 11)
Testing data after cleaning: (64374, 11)
NaN in y_train: 0
NaN in y_test: 0

In [76]:
# ============================================
# CHURNSHIELD - COMPLETE MODEL TRAINING CELL
# ============================================

import pandas as pd
import mlflow

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


# ============================================
# 1. LOAD DATA
# ============================================

train_df = pd.read_csv("../data/raw/train_csv.csv")
test_df = pd.read_csv("../data/raw/test_csv.csv")

print("Training data:", train_df.shape)
print("Testing data :", test_df.shape)


# ============================================
# 2. FIND TARGET COLUMN
# ============================================

possible_targets = ["Churn", "churn", "Exited", "exited"]

target = None

for col in possible_targets:
    if col in train_df.columns:
        target = col
        break

if target is None:
    print("Available columns:")
    print(train_df.columns.tolist())
    raise ValueError("Could not find the churn target column.")

print("Target column:", target)


# ============================================
# 3. REMOVE ROWS WITH MISSING TARGET
# ============================================

train_df = train_df.dropna(subset=[target]).copy()
test_df = test_df.dropna(subset=[target]).copy()

print("Missing target values removed.")
print("Training data:", train_df.shape)
print("Testing data :", test_df.shape)


# ============================================
# 4. SEPARATE FEATURES AND TARGET
# ============================================

X_train = train_df.drop(columns=[target])
y_train = train_df[target]

X_test = test_df.drop(columns=[target])
y_test = test_df[target]


# ============================================
# 5. REMOVE ID COLUMNS
# ============================================

id_columns = [
    "RowNumber",
    "CustomerId",
    "CustomerID",
    "customer_id",
    "id",
    "ID"
]

X_train = X_train.drop(
    columns=[c for c in id_columns if c in X_train.columns],
    errors="ignore"
)

X_test = X_test.drop(
    columns=[c for c in id_columns if c in X_test.columns],
    errors="ignore"
)


# ============================================
# 6. IDENTIFY NUMERIC/CATEGORICAL COLUMNS
# ============================================

numeric_features = X_train.select_dtypes(
    include=["int64", "float64", "int32", "float32"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)


# ============================================
# 7. PREPROCESSING
# ============================================

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])


# ============================================
# 8. DEFINE MODELS
# ============================================

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    
    "Gradient Boosting": GradientBoostingClassifier(
        random_state=42
    )
}


# ============================================
# 9. CONNECT TO MLFLOW
# ============================================

mlflow.set_tracking_uri("http://127.0.0.1:5000")

mlflow.set_experiment("ChurnShield_Model_Experiments")


# ============================================
# 10. TRAIN AND EVALUATE ALL MODELS
# ============================================

results = []

for name, model in models.items():

    print("\n" + "=" * 50)
    print("Training:", name)
    print("=" * 50)

    pipeline = Pipeline([
        ("preprocessing", preprocessor),
        ("model", model)
    ])

    # Train
    pipeline.fit(X_train, y_train)

    # Predict
    predictions = pipeline.predict(X_test)

    # Metrics
    accuracy = accuracy_score(y_test, predictions)

    precision = precision_score(
        y_test,
        predictions,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        average="weighted",
        zero_division=0
    )

    # MLflow logging
    with mlflow.start_run(run_name=name):

        mlflow.log_param("model", name)
        mlflow.log_param("target_column", target)

        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

    # Save results
    results.append({
        "Model": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    })

    print("Model logged successfully!")
    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1 Score : {f1:.4f}")


# ============================================
# 11. MODEL COMPARISON
# ============================================

results_df = pd.DataFrame(results)

print("\n")
print("=" * 60)
print("FINAL MODEL COMPARISON")
print("=" * 60)

display(results_df)


# ============================================
# 12. FIND BEST MODEL
# ============================================

best_model = results_df.loc[
    results_df["F1 Score"].idxmax()
]

print("\nBEST MODEL:")
print(best_model["Model"])

print(f"Best Accuracy: {best_model['Accuracy']:.4f}")
print(f"Best F1 Score : {best_model['F1 Score']:.4f}")

print("\nALL MODELS TRAINED AND LOGGED TO MLFLOW SUCCESSFULLY!")

Training data: (440833, 12)
Testing data : (64374, 12)
Target column: Churn
Missing target values removed.
Training data: (440832, 12)
Testing data : (64374, 12)
Numeric features: ['Age', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction']
Categorical features: ['Gender', 'Subscription Type', 'Contract Length']

C:\Users\Dell\AppData\Local\Temp\ipykernel_13872\65128230.py:104: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X_train.select_dtypes(

==================================================
Training: Logistic Regression
==================================================
🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/1/runs/615d37c5b3884cce932f91de277ec26c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Model logged successfully!
Accuracy : 0.5713
Precision: 0.7531
Recall   : 0.5713
F1 Score : 0.4949

==================================================
Training: Random Forest
==================================================
🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments/1/runs/977927f7fd6d4c1dbc77d6cc9c2fd28c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Model logged successfully!
Accuracy : 0.5040
Precision: 0.7476
Recall   : 0.5040
F1 Score : 0.3691

==================================================
Training: Gradient Boosting
==================================================
🏃 View run Gradient Boosting at: http://127.0.0.1:5000/#/experiments/1/runs/630962f8384e4a9a83d6bfa0db2c8068
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Model logged successfully!
Accuracy : 0.5062
Precision: 0.7458
Recall   : 0.5062
F1 Score : 0.3738


============================================================
FINAL MODEL COMPARISON
============================================================

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.571302   0.753057  0.571302  0.494936
1        Random Forest  0.503977   0.747573  0.503977  0.369071
2    Gradient Boosting  0.506214   0.745777  0.506214  0.373814

BEST MODEL:
Logistic Regression
Best Accuracy: 0.5713
Best F1 Score : 0.4949

ALL MODELS TRAINED AND LOGGED TO MLFLOW SUCCESSFULLY!

In [77]:
import joblib
import os

# Find best model name
best_model_name = results_df.loc[
    results_df["F1 Score"].idxmax(),
    "Model"
]

print("Best model:", best_model_name)

# Get the model object
best_estimator = models[best_model_name]

# Create final pipeline
final_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", best_estimator)
])

# Train final model
final_pipeline.fit(X_train, y_train)

# Make sure models folder exists
os.makedirs("../models", exist_ok=True)

# Save model
joblib.dump(
    final_pipeline,
    "../models/churn_model.pkl"
)

print("Final model saved successfully!")

Best model: Logistic Regression
Final model saved successfully!

In [78]:
results_df.to_csv(
    "../models/model_comparison.csv",
    index=False
)

print("Model comparison saved!")

Model comparison saved!